### PR TITLE
just adding an example somewhere of using a gist of the wdl files

### PR DESCRIPTION
**Pull request by carriewright11**
This is not where we would want this - so we dont want to merge this... but just testing the rendering remotely

### CODE REVIEW

**Comment by carriewright11** [comment]
hmm I don't see it in the preview so I might need to play around with this a bit more - but I think we are onto something :)

**Comment by carriewright11** [comment]
> hmm I don't see it in the preview so I might need to play around with this a bit more - but I think we are onto something :)

sometimes interactive elements don't always show in the preview... I am going to try testing this out somewhere where I can merge

**Comment by aofarrel** [comment]
It may be "stuck" rendering without line breaks due to it not being a proper HTML document? If you preview the WDL file itself, it has no line breaks.
https://htmlpreview.github.io/?https://raw.githubusercontent.com/fhdsl/WDL_Workflows_Guide/preview-21/resources/basic_01.wdl

**Comment by carriewright11** [comment]
Closing this now since I have another PR for more of the wdl files

**Pull request closed without merging**
